Update PyPI GH action

diff --git a/.github/workflows/pypi.yaml b/.github/workflows/pypi.yaml
--- a/.github/workflows/pypi.yaml
+++ b/.github/workflows/pypi.yaml
@@ -1,73 +1,77 @@
-name: Upload ecgtools to PyPI
-
+name: Build and Upload ecgtools to PyPI
 on:
   release:
     types:
       - published
-  workflow_dispatch:
+
 jobs:
-  test-deploy:
+  build-artifacts:
+    runs-on: ubuntu-latest
     if: github.repository == 'NCAR/ecgtools'
-    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Set up Python
-        uses: actions/setup-python@v2
         with:
-          python-version: '3.x'
+          fetch-depth: 0
+      - uses: actions/setup-python@v2
+        name: Install Python
+        with:
+          python-version: 3.8
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           python -m pip install setuptools setuptools-scm wheel twine check-manifest
+
       - name: Build tarball and wheels
         run: |
-          python setup.py sdist bdist_wheel
-          python -m pip wheel . -w dist --no-deps
-      - name: Test the artifacts
+          git clean -xdf
+          git restore -SW .
+          python -m build --sdist --wheel .
+
+      - name: Check built artifacts
         run: |
           python -m twine check dist/*
-
-      - name: Publish package to TestPyPI
-        uses: pypa/gh-action-pypi-publish@v1.4.2
+          pwd
+          if [ -f dist/ecgtools-0.0.0.tar.gz ]; then
+            echo "❌ INVALID VERSION NUMBER"
+            exit 1
+          else
+            echo "✅ Looks good"
+          fi
+      - uses: actions/upload-artifact@v2
         with:
-          user: __token__
-          password: ${{ secrets.TESTPYPI_PASSWORD }}
-          repository_url: https://test.pypi.org/legacy/
-          verbose: true
+          name: releases
+          path: dist
 
-  deploy:
-    needs: test-deploy
-    if: startsWith(github.ref, 'refs/tags')
+  test-built-dist:
+    needs: build-artifacts
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python
-        uses: actions/setup-python@v2
+      - uses: actions/setup-python@v2
+        name: Install Python
         with:
-          python-version: '3.x'
-      - name: Install dependencies
+          python-version: 3.8
+      - uses: actions/download-artifact@v2
+        with:
+          name: releases
+          path: dist
+      - name: List contents of built dist
         run: |
-          python -m pip install --upgrade pip
-          python -m pip install setuptools setuptools-scm wheel twine check-manifest
-      - name: Build tarball and wheels
-        run: |
-          python setup.py sdist bdist_wheel
-          python -m pip wheel . -w dist --no-deps
-      - name: Test the artifacts
-        run: |
-          python -m twine check dist/*
+          ls -ltrh
+          ls -ltrh dist
 
+  upload-to-pypi:
+    needs: test-built-dist
+    if: github.event_name == 'release'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/download-artifact@v2
+        with:
+          name: releases
+          path: dist
       - name: Publish package to PyPI
         uses: pypa/gh-action-pypi-publish@v1.4.2
         with:
-          user: ${{ secrets.PYPI_USERNAME }}
-          password: ${{ secrets.PYPI_PASSWORD }}
-          skip_existing: true
+          user: __token__
+          password: ${{ secrets.PYPI_TOKEN }}
           verbose: true
-
-      # - name: Publish package
-      #   env:
-      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
-      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-      #   run: |
-      #     python -m twine upload dist/* --skip-existing
